[workspace]
members = ["vm", "crates/*"]
exclude = ["riscv/*"]
resolver = "2"

[workspace.dependencies]
riscv-inst = { path = "crates/riscv-inst" }
riscv-inst-macros = { path = "crates/riscv-inst-macros" }