[package]
name = "derisc"
version = "0.1.0"
edition = "2021"

[dependencies]
goblin = "0.9.3"
libc = "0.2.169"
rand = "0.8.5"
riscv-inst.workspace = true
libc-riscv32.workspace = true
syscalls = { version = "0.6.18", features = ["riscv32"] }
thiserror = "2.0.11"
