//! Autogenerated by riscv-inst-codegen
//! DO NOT EDIT

pub use crate::{FReg, Reg};
pub mod rv32;
pub mod rv32a;
pub mod rv32c;
pub mod rv32d;
pub mod rv32f;
pub mod rv32i;
pub mod rv32m;
pub mod rv32q;
pub mod rv32s;
pub mod rv64;
pub mod rv64a;
pub mod rv64c;
pub mod rv64d;
pub mod rv64f;
pub mod rv64i;
pub mod rv64m;
pub mod rv64q;
pub mod rv64s;
