//! Autogenerated by riscv-inst-codegen
//! DO NOT EDIT

pub use super::rv32a::*;
pub use super::rv32c::*;
pub use super::rv32d::*;
pub use super::rv32f::*;
pub use super::rv32i::*;
pub use super::rv32m::*;
pub use super::rv32q::*;
pub use super::rv32s::*;
pub enum Rv32 {
    Rv32q(Rv32q),
    Rv32i(Rv32i),
    Rv32d(Rv32d),
    Rv32m(Rv32m),
    Rv32s(Rv32s),
    Rv32a(Rv32a),
    Rv32f(Rv32f),
    Rv32c(Rv32c),
}
impl Rv32 {
    #[inline(always)]
    pub const fn parse(inst: u32) -> Option<Rv32> {
        match inst & 0b11 {
            0b0 => match (inst >> 13usize) & 0b111 {
                0b0 => Some(Rv32::Rv32c(Rv32c::CAddi4spn(CAddi4spn(inst as _)))),
                0b1 => Some(Rv32::Rv32c(Rv32c::CFld(CFld(inst as _)))),
                0b10 => Some(Rv32::Rv32c(Rv32c::CLw(CLw(inst as _)))),
                0b11 => Some(Rv32::Rv32c(Rv32c::CFlw(CFlw(inst as _)))),
                0b101 => Some(Rv32::Rv32c(Rv32c::CFsd(CFsd(inst as _)))),
                0b110 => Some(Rv32::Rv32c(Rv32c::CSw(CSw(inst as _)))),
                0b111 => Some(Rv32::Rv32c(Rv32c::CFsw(CFsw(inst as _)))),
                _ => None,
            },
            0b1 => match (inst >> 13usize) & 0b111 {
                0b0 if ((inst >> 12usize) & 0b1) == 0
                    && ((inst >> 7usize) & 0b11111) == 0
                    && ((inst >> 2usize) & 0b11111) == 0 =>
                {
                    Some(Rv32::Rv32c(Rv32c::CNop(CNop(inst as _))))
                }
                0b0 => Some(Rv32::Rv32c(Rv32c::CAddi(CAddi(inst as _)))),
                0b1 => Some(Rv32::Rv32c(Rv32c::CJal(CJal(inst as _)))),
                0b10 => Some(Rv32::Rv32c(Rv32c::CLi(CLi(inst as _)))),
                0b11 if ((inst >> 7usize) & 0b11111) == 2 => {
                    Some(Rv32::Rv32c(Rv32c::CAddi16sp(CAddi16sp(inst as _))))
                }
                0b11 => Some(Rv32::Rv32c(Rv32c::CLui(CLui(inst as _)))),
                0b100 => match (inst >> 10usize) & 0b11 {
                    0b0 => Some(Rv32::Rv32c(Rv32c::CSrli(CSrli(inst as _)))),
                    0b1 => Some(Rv32::Rv32c(Rv32c::CSrai(CSrai(inst as _)))),
                    0b10 => Some(Rv32::Rv32c(Rv32c::CAndi(CAndi(inst as _)))),
                    0b11 => match (inst >> 5usize) & 0b11 {
                        0b0 => match (inst >> 12usize) & 0b1 {
                            0b0 => Some(Rv32::Rv32c(Rv32c::CSub(CSub(inst as _)))),
                            0b1 => Some(Rv32::Rv32c(Rv32c::CSubw(CSubw(inst as _)))),
                            _ => None,
                        },
                        0b1 => match (inst >> 12usize) & 0b1 {
                            0b0 => Some(Rv32::Rv32c(Rv32c::CXor(CXor(inst as _)))),
                            0b1 => Some(Rv32::Rv32c(Rv32c::CAddw(CAddw(inst as _)))),
                            _ => None,
                        },
                        0b10 => Some(Rv32::Rv32c(Rv32c::COr(COr(inst as _)))),
                        0b11 => Some(Rv32::Rv32c(Rv32c::CAnd(CAnd(inst as _)))),
                        _ => None,
                    },
                    _ => None,
                },
                0b101 => Some(Rv32::Rv32c(Rv32c::CJ(CJ(inst as _)))),
                0b110 => Some(Rv32::Rv32c(Rv32c::CBeqz(CBeqz(inst as _)))),
                0b111 => Some(Rv32::Rv32c(Rv32c::CBnez(CBnez(inst as _)))),
                _ => None,
            },
            0b10 => match (inst >> 13usize) & 0b111 {
                0b0 => Some(Rv32::Rv32c(Rv32c::CSlli(CSlli(inst as _)))),
                0b1 => Some(Rv32::Rv32c(Rv32c::CFldsp(CFldsp(inst as _)))),
                0b10 => Some(Rv32::Rv32c(Rv32c::CLwsp(CLwsp(inst as _)))),
                0b11 => Some(Rv32::Rv32c(Rv32c::CFlwsp(CFlwsp(inst as _)))),
                0b100 => match (inst >> 12usize) & 0b1 {
                    0b0 if ((inst >> 2usize) & 0b11111) == 0 => {
                        Some(Rv32::Rv32c(Rv32c::CJr(CJr(inst as _))))
                    }
                    0b0 => Some(Rv32::Rv32c(Rv32c::CMv(CMv(inst as _)))),
                    0b1 if ((inst >> 7usize) & 0b11111) == 0
                        && ((inst >> 2usize) & 0b11111) == 0 =>
                    {
                        Some(Rv32::Rv32c(Rv32c::CEbreak(CEbreak(inst as _))))
                    }
                    0b1 if ((inst >> 2usize) & 0b11111) == 0 => {
                        Some(Rv32::Rv32c(Rv32c::CJalr(CJalr(inst as _))))
                    }
                    0b1 => Some(Rv32::Rv32c(Rv32c::CAdd(CAdd(inst as _)))),
                    _ => None,
                },
                0b101 => Some(Rv32::Rv32c(Rv32c::CFsdsp(CFsdsp(inst as _)))),
                0b110 => Some(Rv32::Rv32c(Rv32c::CSwsp(CSwsp(inst as _)))),
                0b111 => Some(Rv32::Rv32c(Rv32c::CFswsp(CFswsp(inst as _)))),
                _ => None,
            },
            0b11 => match (inst >> 2usize) & 0b11111 {
                0b000 => match (inst >> 12usize) & 0b111 {
                    0b0 => Some(Rv32::Rv32i(Rv32i::Lb(Lb(inst as _)))),
                    0b1 => Some(Rv32::Rv32i(Rv32i::Lh(Lh(inst as _)))),
                    0b10 => Some(Rv32::Rv32i(Rv32i::Lw(Lw(inst as _)))),
                    0b100 => Some(Rv32::Rv32i(Rv32i::Lbu(Lbu(inst as _)))),
                    0b101 => Some(Rv32::Rv32i(Rv32i::Lhu(Lhu(inst as _)))),
                    _ => None,
                },
                0b001 => match (inst >> 12usize) & 0b111 {
                    0b10 => Some(Rv32::Rv32f(Rv32f::Flw(Flw(inst as _)))),
                    0b11 => Some(Rv32::Rv32d(Rv32d::Fld(Fld(inst as _)))),
                    0b100 => Some(Rv32::Rv32q(Rv32q::Flq(Flq(inst as _)))),
                    _ => None,
                },
                0b011 => match (inst >> 12usize) & 0b111 {
                    0b0 => Some(Rv32::Rv32i(Rv32i::Fence(Fence(inst as _)))),
                    0b1 => Some(Rv32::Rv32i(Rv32i::FenceI(FenceI(inst as _)))),
                    _ => None,
                },
                0b100 => match (inst >> 12usize) & 0b111 {
                    0b0 => Some(Rv32::Rv32i(Rv32i::Addi(Addi(inst as _)))),
                    0b1 => Some(Rv32::Rv32i(Rv32i::Slli(Slli(inst as _)))),
                    0b10 => Some(Rv32::Rv32i(Rv32i::Slti(Slti(inst as _)))),
                    0b11 => Some(Rv32::Rv32i(Rv32i::Sltiu(Sltiu(inst as _)))),
                    0b100 => Some(Rv32::Rv32i(Rv32i::Xori(Xori(inst as _)))),
                    0b101 => match (inst >> 27usize) & 0b11111 {
                        0b000 => Some(Rv32::Rv32i(Rv32i::Srli(Srli(inst as _)))),
                        0b1000 => Some(Rv32::Rv32i(Rv32i::Srai(Srai(inst as _)))),
                        _ => None,
                    },
                    0b110 => Some(Rv32::Rv32i(Rv32i::Ori(Ori(inst as _)))),
                    0b111 => Some(Rv32::Rv32i(Rv32i::Andi(Andi(inst as _)))),
                    _ => None,
                },
                0b101 => Some(Rv32::Rv32i(Rv32i::Auipc(Auipc(inst as _)))),
                0b1000 => match (inst >> 12usize) & 0b111 {
                    0b0 => Some(Rv32::Rv32i(Rv32i::Sb(Sb(inst as _)))),
                    0b1 => Some(Rv32::Rv32i(Rv32i::Sh(Sh(inst as _)))),
                    0b10 => Some(Rv32::Rv32i(Rv32i::Sw(Sw(inst as _)))),
                    _ => None,
                },
                0b1001 => match (inst >> 12usize) & 0b111 {
                    0b10 => Some(Rv32::Rv32f(Rv32f::Fsw(Fsw(inst as _)))),
                    0b11 => Some(Rv32::Rv32d(Rv32d::Fsd(Fsd(inst as _)))),
                    0b100 => Some(Rv32::Rv32q(Rv32q::Fsq(Fsq(inst as _)))),
                    _ => None,
                },
                0b1011 => match (inst >> 29usize) & 0b111 {
                    0b0 => match (inst >> 27usize) & 0b11 {
                        0b0 => Some(Rv32::Rv32a(Rv32a::AmoaddW(AmoaddW(inst as _)))),
                        0b1 => Some(Rv32::Rv32a(Rv32a::AmoswapW(AmoswapW(inst as _)))),
                        0b10 => Some(Rv32::Rv32a(Rv32a::LrW(LrW(inst as _)))),
                        0b11 => Some(Rv32::Rv32a(Rv32a::ScW(ScW(inst as _)))),
                        _ => None,
                    },
                    0b1 => Some(Rv32::Rv32a(Rv32a::AmoxorW(AmoxorW(inst as _)))),
                    0b10 => Some(Rv32::Rv32a(Rv32a::AmoorW(AmoorW(inst as _)))),
                    0b11 => Some(Rv32::Rv32a(Rv32a::AmoandW(AmoandW(inst as _)))),
                    0b100 => Some(Rv32::Rv32a(Rv32a::AmominW(AmominW(inst as _)))),
                    0b101 => Some(Rv32::Rv32a(Rv32a::AmomaxW(AmomaxW(inst as _)))),
                    0b110 => Some(Rv32::Rv32a(Rv32a::AmominuW(AmominuW(inst as _)))),
                    0b111 => Some(Rv32::Rv32a(Rv32a::AmomaxuW(AmomaxuW(inst as _)))),
                    _ => None,
                },
                0b1100 => match (inst >> 12usize) & 0b111 {
                    0b0 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv32::Rv32i(Rv32i::Add(Add(inst as _)))),
                        0b00001 => Some(Rv32::Rv32m(Rv32m::Mul(Mul(inst as _)))),
                        0b100000 => Some(Rv32::Rv32i(Rv32i::Sub(Sub(inst as _)))),
                        _ => None,
                    },
                    0b1 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv32::Rv32i(Rv32i::Sll(Sll(inst as _)))),
                        0b00001 => Some(Rv32::Rv32m(Rv32m::Mulh(Mulh(inst as _)))),
                        _ => None,
                    },
                    0b10 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv32::Rv32i(Rv32i::Slt(Slt(inst as _)))),
                        0b00001 => Some(Rv32::Rv32m(Rv32m::Mulhsu(Mulhsu(inst as _)))),
                        _ => None,
                    },
                    0b11 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv32::Rv32i(Rv32i::Sltu(Sltu(inst as _)))),
                        0b00001 => Some(Rv32::Rv32m(Rv32m::Mulhu(Mulhu(inst as _)))),
                        _ => None,
                    },
                    0b100 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv32::Rv32i(Rv32i::Xor(Xor(inst as _)))),
                        0b00001 => Some(Rv32::Rv32m(Rv32m::Div(Div(inst as _)))),
                        _ => None,
                    },
                    0b101 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv32::Rv32i(Rv32i::Srl(Srl(inst as _)))),
                        0b00001 => Some(Rv32::Rv32m(Rv32m::Divu(Divu(inst as _)))),
                        0b100000 => Some(Rv32::Rv32i(Rv32i::Sra(Sra(inst as _)))),
                        _ => None,
                    },
                    0b110 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv32::Rv32i(Rv32i::Or(Or(inst as _)))),
                        0b00001 => Some(Rv32::Rv32m(Rv32m::Rem(Rem(inst as _)))),
                        _ => None,
                    },
                    0b111 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv32::Rv32i(Rv32i::And(And(inst as _)))),
                        0b00001 => Some(Rv32::Rv32m(Rv32m::Remu(Remu(inst as _)))),
                        _ => None,
                    },
                    _ => None,
                },
                0b1101 => Some(Rv32::Rv32i(Rv32i::Lui(Lui(inst as _)))),
                0b10000 => match (inst >> 25usize) & 0b11 {
                    0b0 => Some(Rv32::Rv32f(Rv32f::FmaddS(FmaddS(inst as _)))),
                    0b1 => Some(Rv32::Rv32d(Rv32d::FmaddD(FmaddD(inst as _)))),
                    0b11 => Some(Rv32::Rv32q(Rv32q::FmaddQ(FmaddQ(inst as _)))),
                    _ => None,
                },
                0b10001 => match (inst >> 25usize) & 0b11 {
                    0b0 => Some(Rv32::Rv32f(Rv32f::FmsubS(FmsubS(inst as _)))),
                    0b1 => Some(Rv32::Rv32d(Rv32d::FmsubD(FmsubD(inst as _)))),
                    0b11 => Some(Rv32::Rv32q(Rv32q::FmsubQ(FmsubQ(inst as _)))),
                    _ => None,
                },
                0b10010 => match (inst >> 25usize) & 0b11 {
                    0b0 => Some(Rv32::Rv32f(Rv32f::FnmsubS(FnmsubS(inst as _)))),
                    0b1 => Some(Rv32::Rv32d(Rv32d::FnmsubD(FnmsubD(inst as _)))),
                    0b11 => Some(Rv32::Rv32q(Rv32q::FnmsubQ(FnmsubQ(inst as _)))),
                    _ => None,
                },
                0b10011 => match (inst >> 25usize) & 0b11 {
                    0b0 => Some(Rv32::Rv32f(Rv32f::FnmaddS(FnmaddS(inst as _)))),
                    0b1 => Some(Rv32::Rv32d(Rv32d::FnmaddD(FnmaddD(inst as _)))),
                    0b11 => Some(Rv32::Rv32q(Rv32q::FnmaddQ(FnmaddQ(inst as _)))),
                    _ => None,
                },
                0b10100 => match (inst >> 27usize) & 0b11111 {
                    0b000 => match (inst >> 25usize) & 0b11 {
                        0b0 => Some(Rv32::Rv32f(Rv32f::FaddS(FaddS(inst as _)))),
                        0b1 => Some(Rv32::Rv32d(Rv32d::FaddD(FaddD(inst as _)))),
                        0b11 => Some(Rv32::Rv32q(Rv32q::FaddQ(FaddQ(inst as _)))),
                        _ => None,
                    },
                    0b001 => match (inst >> 25usize) & 0b11 {
                        0b0 => Some(Rv32::Rv32f(Rv32f::FsubS(FsubS(inst as _)))),
                        0b1 => Some(Rv32::Rv32d(Rv32d::FsubD(FsubD(inst as _)))),
                        0b11 => Some(Rv32::Rv32q(Rv32q::FsubQ(FsubQ(inst as _)))),
                        _ => None,
                    },
                    0b010 => match (inst >> 25usize) & 0b11 {
                        0b0 => Some(Rv32::Rv32f(Rv32f::FmulS(FmulS(inst as _)))),
                        0b1 => Some(Rv32::Rv32d(Rv32d::FmulD(FmulD(inst as _)))),
                        0b11 => Some(Rv32::Rv32q(Rv32q::FmulQ(FmulQ(inst as _)))),
                        _ => None,
                    },
                    0b011 => match (inst >> 25usize) & 0b11 {
                        0b0 => Some(Rv32::Rv32f(Rv32f::FdivS(FdivS(inst as _)))),
                        0b1 => Some(Rv32::Rv32d(Rv32d::FdivD(FdivD(inst as _)))),
                        0b11 => Some(Rv32::Rv32q(Rv32q::FdivQ(FdivQ(inst as _)))),
                        _ => None,
                    },
                    0b100 => match (inst >> 25usize) & 0b11 {
                        0b0 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv32::Rv32f(Rv32f::FsgnjS(FsgnjS(inst as _)))),
                            0b1 => Some(Rv32::Rv32f(Rv32f::FsgnjnS(FsgnjnS(inst as _)))),
                            0b10 => Some(Rv32::Rv32f(Rv32f::FsgnjxS(FsgnjxS(inst as _)))),
                            _ => None,
                        },
                        0b1 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv32::Rv32d(Rv32d::FsgnjD(FsgnjD(inst as _)))),
                            0b1 => Some(Rv32::Rv32d(Rv32d::FsgnjnD(FsgnjnD(inst as _)))),
                            0b10 => Some(Rv32::Rv32d(Rv32d::FsgnjxD(FsgnjxD(inst as _)))),
                            _ => None,
                        },
                        0b11 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv32::Rv32q(Rv32q::FsgnjQ(FsgnjQ(inst as _)))),
                            0b1 => Some(Rv32::Rv32q(Rv32q::FsgnjnQ(FsgnjnQ(inst as _)))),
                            0b10 => Some(Rv32::Rv32q(Rv32q::FsgnjxQ(FsgnjxQ(inst as _)))),
                            _ => None,
                        },
                        _ => None,
                    },
                    0b101 => match (inst >> 25usize) & 0b11 {
                        0b0 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv32::Rv32f(Rv32f::FminS(FminS(inst as _)))),
                            0b1 => Some(Rv32::Rv32f(Rv32f::FmaxS(FmaxS(inst as _)))),
                            _ => None,
                        },
                        0b1 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv32::Rv32d(Rv32d::FminD(FminD(inst as _)))),
                            0b1 => Some(Rv32::Rv32d(Rv32d::FmaxD(FmaxD(inst as _)))),
                            _ => None,
                        },
                        0b11 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv32::Rv32q(Rv32q::FminQ(FminQ(inst as _)))),
                            0b1 => Some(Rv32::Rv32q(Rv32q::FmaxQ(FmaxQ(inst as _)))),
                            _ => None,
                        },
                        _ => None,
                    },
                    0b1000 => match (inst >> 25usize) & 0b11 {
                        0b0 => match (inst >> 20usize) & 0b11111 {
                            0b001 => Some(Rv32::Rv32d(Rv32d::FcvtSD(FcvtSD(inst as _)))),
                            0b011 => Some(Rv32::Rv32q(Rv32q::FcvtSQ(FcvtSQ(inst as _)))),
                            _ => None,
                        },
                        0b1 => match (inst >> 20usize) & 0b11111 {
                            0b000 => Some(Rv32::Rv32d(Rv32d::FcvtDS(FcvtDS(inst as _)))),
                            0b011 => Some(Rv32::Rv32q(Rv32q::FcvtDQ(FcvtDQ(inst as _)))),
                            _ => None,
                        },
                        0b11 => match (inst >> 20usize) & 0b11111 {
                            0b000 => Some(Rv32::Rv32q(Rv32q::FcvtQS(FcvtQS(inst as _)))),
                            0b001 => Some(Rv32::Rv32q(Rv32q::FcvtQD(FcvtQD(inst as _)))),
                            _ => None,
                        },
                        _ => None,
                    },
                    0b1011 => match (inst >> 25usize) & 0b11 {
                        0b0 => Some(Rv32::Rv32f(Rv32f::FsqrtS(FsqrtS(inst as _)))),
                        0b1 => Some(Rv32::Rv32d(Rv32d::FsqrtD(FsqrtD(inst as _)))),
                        0b11 => Some(Rv32::Rv32q(Rv32q::FsqrtQ(FsqrtQ(inst as _)))),
                        _ => None,
                    },
                    0b10100 => match (inst >> 25usize) & 0b11 {
                        0b0 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv32::Rv32f(Rv32f::FleS(FleS(inst as _)))),
                            0b1 => Some(Rv32::Rv32f(Rv32f::FltS(FltS(inst as _)))),
                            0b10 => Some(Rv32::Rv32f(Rv32f::FeqS(FeqS(inst as _)))),
                            _ => None,
                        },
                        0b1 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv32::Rv32d(Rv32d::FleD(FleD(inst as _)))),
                            0b1 => Some(Rv32::Rv32d(Rv32d::FltD(FltD(inst as _)))),
                            0b10 => Some(Rv32::Rv32d(Rv32d::FeqD(FeqD(inst as _)))),
                            _ => None,
                        },
                        0b11 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv32::Rv32q(Rv32q::FleQ(FleQ(inst as _)))),
                            0b1 => Some(Rv32::Rv32q(Rv32q::FltQ(FltQ(inst as _)))),
                            0b10 => Some(Rv32::Rv32q(Rv32q::FeqQ(FeqQ(inst as _)))),
                            _ => None,
                        },
                        _ => None,
                    },
                    0b11000 => match (inst >> 25usize) & 0b11 {
                        0b0 => match (inst >> 20usize) & 0b11111 {
                            0b000 => Some(Rv32::Rv32f(Rv32f::FcvtWS(FcvtWS(inst as _)))),
                            0b001 => Some(Rv32::Rv32f(Rv32f::FcvtWuS(FcvtWuS(inst as _)))),
                            _ => None,
                        },
                        0b1 => match (inst >> 20usize) & 0b11111 {
                            0b000 => Some(Rv32::Rv32d(Rv32d::FcvtWD(FcvtWD(inst as _)))),
                            0b001 => Some(Rv32::Rv32d(Rv32d::FcvtWuD(FcvtWuD(inst as _)))),
                            _ => None,
                        },
                        0b11 => match (inst >> 20usize) & 0b11111 {
                            0b000 => Some(Rv32::Rv32q(Rv32q::FcvtWQ(FcvtWQ(inst as _)))),
                            0b001 => Some(Rv32::Rv32q(Rv32q::FcvtWuQ(FcvtWuQ(inst as _)))),
                            _ => None,
                        },
                        _ => None,
                    },
                    0b11010 => match (inst >> 25usize) & 0b11 {
                        0b0 => match (inst >> 20usize) & 0b11111 {
                            0b000 => Some(Rv32::Rv32f(Rv32f::FcvtSW(FcvtSW(inst as _)))),
                            0b001 => Some(Rv32::Rv32f(Rv32f::FcvtSWu(FcvtSWu(inst as _)))),
                            _ => None,
                        },
                        0b1 => match (inst >> 20usize) & 0b11111 {
                            0b000 => Some(Rv32::Rv32d(Rv32d::FcvtDW(FcvtDW(inst as _)))),
                            0b001 => Some(Rv32::Rv32d(Rv32d::FcvtDWu(FcvtDWu(inst as _)))),
                            _ => None,
                        },
                        0b11 => match (inst >> 20usize) & 0b11111 {
                            0b000 => Some(Rv32::Rv32q(Rv32q::FcvtQW(FcvtQW(inst as _)))),
                            0b001 => Some(Rv32::Rv32q(Rv32q::FcvtQWu(FcvtQWu(inst as _)))),
                            _ => None,
                        },
                        _ => None,
                    },
                    0b11100 => match (inst >> 25usize) & 0b11 {
                        0b0 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv32::Rv32f(Rv32f::FmvXS(FmvXS(inst as _)))),
                            0b1 => Some(Rv32::Rv32f(Rv32f::FclassS(FclassS(inst as _)))),
                            _ => None,
                        },
                        0b1 => Some(Rv32::Rv32d(Rv32d::FclassD(FclassD(inst as _)))),
                        0b11 => Some(Rv32::Rv32q(Rv32q::FclassQ(FclassQ(inst as _)))),
                        _ => None,
                    },
                    0b11110 => Some(Rv32::Rv32f(Rv32f::FmvSX(FmvSX(inst as _)))),
                    _ => None,
                },
                0b11000 => match (inst >> 12usize) & 0b111 {
                    0b0 => Some(Rv32::Rv32i(Rv32i::Beq(Beq(inst as _)))),
                    0b1 => Some(Rv32::Rv32i(Rv32i::Bne(Bne(inst as _)))),
                    0b100 => Some(Rv32::Rv32i(Rv32i::Blt(Blt(inst as _)))),
                    0b101 => Some(Rv32::Rv32i(Rv32i::Bge(Bge(inst as _)))),
                    0b110 => Some(Rv32::Rv32i(Rv32i::Bltu(Bltu(inst as _)))),
                    0b111 => Some(Rv32::Rv32i(Rv32i::Bgeu(Bgeu(inst as _)))),
                    _ => None,
                },
                0b11001 => Some(Rv32::Rv32i(Rv32i::Jalr(Jalr(inst as _)))),
                0b11011 => Some(Rv32::Rv32i(Rv32i::Jal(Jal(inst as _)))),
                0b11100 => match (inst >> 12usize) & 0b111 {
                    0b0 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => match (inst >> 20usize) & 0b11111 {
                            0b000 => Some(Rv32::Rv32s(Rv32s::Ecall(Ecall(inst as _)))),
                            0b001 => Some(Rv32::Rv32s(Rv32s::Ebreak(Ebreak(inst as _)))),
                            0b010 => Some(Rv32::Rv32s(Rv32s::Uret(Uret(inst as _)))),
                            _ => None,
                        },
                        0b01000 => match (inst >> 20usize) & 0b11111 {
                            0b010 => Some(Rv32::Rv32s(Rv32s::Sret(Sret(inst as _)))),
                            0b100 => Some(Rv32::Rv32s(Rv32s::SfenceVm(SfenceVm(inst as _)))),
                            0b101 => Some(Rv32::Rv32s(Rv32s::Wfi(Wfi(inst as _)))),
                            _ => None,
                        },
                        0b01001 => Some(Rv32::Rv32s(Rv32s::SfenceVma(SfenceVma(inst as _)))),
                        0b10000 => Some(Rv32::Rv32s(Rv32s::Hret(Hret(inst as _)))),
                        0b11000 => Some(Rv32::Rv32s(Rv32s::Mret(Mret(inst as _)))),
                        0b111101 => Some(Rv32::Rv32s(Rv32s::Dret(Dret(inst as _)))),
                        _ => None,
                    },
                    0b1 => Some(Rv32::Rv32s(Rv32s::Csrrw(Csrrw(inst as _)))),
                    0b10 => Some(Rv32::Rv32s(Rv32s::Csrrs(Csrrs(inst as _)))),
                    0b11 => Some(Rv32::Rv32s(Rv32s::Csrrc(Csrrc(inst as _)))),
                    0b101 => Some(Rv32::Rv32s(Rv32s::Csrrwi(Csrrwi(inst as _)))),
                    0b110 => Some(Rv32::Rv32s(Rv32s::Csrrsi(Csrrsi(inst as _)))),
                    0b111 => Some(Rv32::Rv32s(Rv32s::Csrrci(Csrrci(inst as _)))),
                    _ => None,
                },
                _ => None,
            },
            _ => None,
        }
    }
}
