//! Autogenerated by riscv-inst-codegen
//! DO NOT EDIT

pub use super::rv64a::*;
pub use super::rv64c::*;
pub use super::rv64d::*;
pub use super::rv64f::*;
pub use super::rv64i::*;
pub use super::rv64m::*;
pub use super::rv64q::*;
pub use super::rv64s::*;
pub enum Rv64 {
    Rv64s(Rv64s),
    Rv64d(Rv64d),
    Rv64q(Rv64q),
    Rv64c(Rv64c),
    Rv64i(Rv64i),
    Rv64f(Rv64f),
    Rv64a(Rv64a),
    Rv64m(Rv64m),
}
impl Rv64 {
    #[inline(always)]
    pub const fn parse(inst: u32) -> Option<Rv64> {
        match inst & 0b11 {
            0b0 => match (inst >> 13usize) & 0b111 {
                0b0 => Some(Rv64::Rv64c(Rv64c::CAddi4spn(CAddi4spn(inst as _)))),
                0b1 => Some(Rv64::Rv64c(Rv64c::CFld(CFld(inst as _)))),
                0b10 => Some(Rv64::Rv64c(Rv64c::CLw(CLw(inst as _)))),
                0b11 => Some(Rv64::Rv64c(Rv64c::CLd(CLd(inst as _)))),
                0b101 => Some(Rv64::Rv64c(Rv64c::CFsd(CFsd(inst as _)))),
                0b110 => Some(Rv64::Rv64c(Rv64c::CSw(CSw(inst as _)))),
                0b111 => Some(Rv64::Rv64c(Rv64c::CSd(CSd(inst as _)))),
                _ => None,
            },
            0b1 => match (inst >> 13usize) & 0b111 {
                0b0 if ((inst >> 12usize) & 0b1) == 0
                    && ((inst >> 7usize) & 0b11111) == 0
                    && ((inst >> 2usize) & 0b11111) == 0 =>
                {
                    Some(Rv64::Rv64c(Rv64c::CNop(CNop(inst as _))))
                }
                0b0 => Some(Rv64::Rv64c(Rv64c::CAddi(CAddi(inst as _)))),
                0b1 => Some(Rv64::Rv64c(Rv64c::CAddiw(CAddiw(inst as _)))),
                0b10 => Some(Rv64::Rv64c(Rv64c::CLi(CLi(inst as _)))),
                0b11 if ((inst >> 7usize) & 0b11111) == 2 => {
                    Some(Rv64::Rv64c(Rv64c::CAddi16sp(CAddi16sp(inst as _))))
                }
                0b11 => Some(Rv64::Rv64c(Rv64c::CLui(CLui(inst as _)))),
                0b100 => match (inst >> 10usize) & 0b11 {
                    0b0 => Some(Rv64::Rv64c(Rv64c::CSrli(CSrli(inst as _)))),
                    0b1 => Some(Rv64::Rv64c(Rv64c::CSrai(CSrai(inst as _)))),
                    0b10 => Some(Rv64::Rv64c(Rv64c::CAndi(CAndi(inst as _)))),
                    0b11 => match (inst >> 5usize) & 0b11 {
                        0b0 => match (inst >> 12usize) & 0b1 {
                            0b0 => Some(Rv64::Rv64c(Rv64c::CSub(CSub(inst as _)))),
                            0b1 => Some(Rv64::Rv64c(Rv64c::CSubw(CSubw(inst as _)))),
                            _ => None,
                        },
                        0b1 => match (inst >> 12usize) & 0b1 {
                            0b0 => Some(Rv64::Rv64c(Rv64c::CXor(CXor(inst as _)))),
                            0b1 => Some(Rv64::Rv64c(Rv64c::CAddw(CAddw(inst as _)))),
                            _ => None,
                        },
                        0b10 => Some(Rv64::Rv64c(Rv64c::COr(COr(inst as _)))),
                        0b11 => Some(Rv64::Rv64c(Rv64c::CAnd(CAnd(inst as _)))),
                        _ => None,
                    },
                    _ => None,
                },
                0b101 => Some(Rv64::Rv64c(Rv64c::CJ(CJ(inst as _)))),
                0b110 => Some(Rv64::Rv64c(Rv64c::CBeqz(CBeqz(inst as _)))),
                0b111 => Some(Rv64::Rv64c(Rv64c::CBnez(CBnez(inst as _)))),
                _ => None,
            },
            0b10 => match (inst >> 13usize) & 0b111 {
                0b0 => Some(Rv64::Rv64c(Rv64c::CSlli(CSlli(inst as _)))),
                0b1 => Some(Rv64::Rv64c(Rv64c::CFldsp(CFldsp(inst as _)))),
                0b10 => Some(Rv64::Rv64c(Rv64c::CLwsp(CLwsp(inst as _)))),
                0b11 => Some(Rv64::Rv64c(Rv64c::CLdsp(CLdsp(inst as _)))),
                0b100 => match (inst >> 12usize) & 0b1 {
                    0b0 if ((inst >> 2usize) & 0b11111) == 0 => {
                        Some(Rv64::Rv64c(Rv64c::CJr(CJr(inst as _))))
                    }
                    0b0 => Some(Rv64::Rv64c(Rv64c::CMv(CMv(inst as _)))),
                    0b1 if ((inst >> 7usize) & 0b11111) == 0
                        && ((inst >> 2usize) & 0b11111) == 0 =>
                    {
                        Some(Rv64::Rv64c(Rv64c::CEbreak(CEbreak(inst as _))))
                    }
                    0b1 if ((inst >> 2usize) & 0b11111) == 0 => {
                        Some(Rv64::Rv64c(Rv64c::CJalr(CJalr(inst as _))))
                    }
                    0b1 => Some(Rv64::Rv64c(Rv64c::CAdd(CAdd(inst as _)))),
                    _ => None,
                },
                0b101 => Some(Rv64::Rv64c(Rv64c::CFsdsp(CFsdsp(inst as _)))),
                0b110 => Some(Rv64::Rv64c(Rv64c::CSwsp(CSwsp(inst as _)))),
                0b111 => Some(Rv64::Rv64c(Rv64c::CSdsp(CSdsp(inst as _)))),
                _ => None,
            },
            0b11 => match (inst >> 2usize) & 0b11111 {
                0b000 => match (inst >> 12usize) & 0b111 {
                    0b0 => Some(Rv64::Rv64i(Rv64i::Lb(Lb(inst as _)))),
                    0b1 => Some(Rv64::Rv64i(Rv64i::Lh(Lh(inst as _)))),
                    0b10 => Some(Rv64::Rv64i(Rv64i::Lw(Lw(inst as _)))),
                    0b11 => Some(Rv64::Rv64i(Rv64i::Ld(Ld(inst as _)))),
                    0b100 => Some(Rv64::Rv64i(Rv64i::Lbu(Lbu(inst as _)))),
                    0b101 => Some(Rv64::Rv64i(Rv64i::Lhu(Lhu(inst as _)))),
                    0b110 => Some(Rv64::Rv64i(Rv64i::Lwu(Lwu(inst as _)))),
                    _ => None,
                },
                0b001 => match (inst >> 12usize) & 0b111 {
                    0b10 => Some(Rv64::Rv64f(Rv64f::Flw(Flw(inst as _)))),
                    0b11 => Some(Rv64::Rv64d(Rv64d::Fld(Fld(inst as _)))),
                    0b100 => Some(Rv64::Rv64q(Rv64q::Flq(Flq(inst as _)))),
                    _ => None,
                },
                0b011 => match (inst >> 12usize) & 0b111 {
                    0b0 => Some(Rv64::Rv64i(Rv64i::Fence(Fence(inst as _)))),
                    0b1 => Some(Rv64::Rv64i(Rv64i::FenceI(FenceI(inst as _)))),
                    _ => None,
                },
                0b100 => match (inst >> 12usize) & 0b111 {
                    0b0 => Some(Rv64::Rv64i(Rv64i::Addi(Addi(inst as _)))),
                    0b1 => Some(Rv64::Rv64i(Rv64i::Slli(Slli(inst as _)))),
                    0b10 => Some(Rv64::Rv64i(Rv64i::Slti(Slti(inst as _)))),
                    0b11 => Some(Rv64::Rv64i(Rv64i::Sltiu(Sltiu(inst as _)))),
                    0b100 => Some(Rv64::Rv64i(Rv64i::Xori(Xori(inst as _)))),
                    0b101 => match (inst >> 27usize) & 0b11111 {
                        0b000 => Some(Rv64::Rv64i(Rv64i::Srli(Srli(inst as _)))),
                        0b1000 => Some(Rv64::Rv64i(Rv64i::Srai(Srai(inst as _)))),
                        _ => None,
                    },
                    0b110 => Some(Rv64::Rv64i(Rv64i::Ori(Ori(inst as _)))),
                    0b111 => Some(Rv64::Rv64i(Rv64i::Andi(Andi(inst as _)))),
                    _ => None,
                },
                0b101 => Some(Rv64::Rv64i(Rv64i::Auipc(Auipc(inst as _)))),
                0b110 => match (inst >> 12usize) & 0b111 {
                    0b0 => Some(Rv64::Rv64i(Rv64i::Addiw(Addiw(inst as _)))),
                    0b1 => Some(Rv64::Rv64i(Rv64i::Slliw(Slliw(inst as _)))),
                    0b101 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv64::Rv64i(Rv64i::Srliw(Srliw(inst as _)))),
                        0b100000 => Some(Rv64::Rv64i(Rv64i::Sraiw(Sraiw(inst as _)))),
                        _ => None,
                    },
                    _ => None,
                },
                0b1000 => match (inst >> 12usize) & 0b111 {
                    0b0 => Some(Rv64::Rv64i(Rv64i::Sb(Sb(inst as _)))),
                    0b1 => Some(Rv64::Rv64i(Rv64i::Sh(Sh(inst as _)))),
                    0b10 => Some(Rv64::Rv64i(Rv64i::Sw(Sw(inst as _)))),
                    0b11 => Some(Rv64::Rv64i(Rv64i::Sd(Sd(inst as _)))),
                    _ => None,
                },
                0b1001 => match (inst >> 12usize) & 0b111 {
                    0b10 => Some(Rv64::Rv64f(Rv64f::Fsw(Fsw(inst as _)))),
                    0b11 => Some(Rv64::Rv64d(Rv64d::Fsd(Fsd(inst as _)))),
                    0b100 => Some(Rv64::Rv64q(Rv64q::Fsq(Fsq(inst as _)))),
                    _ => None,
                },
                0b1011 => match (inst >> 29usize) & 0b111 {
                    0b0 => match (inst >> 27usize) & 0b11 {
                        0b0 => match (inst >> 12usize) & 0b111 {
                            0b10 => Some(Rv64::Rv64a(Rv64a::AmoaddW(AmoaddW(inst as _)))),
                            0b11 => Some(Rv64::Rv64a(Rv64a::AmoaddD(AmoaddD(inst as _)))),
                            _ => None,
                        },
                        0b1 => match (inst >> 12usize) & 0b111 {
                            0b10 => Some(Rv64::Rv64a(Rv64a::AmoswapW(AmoswapW(inst as _)))),
                            0b11 => Some(Rv64::Rv64a(Rv64a::AmoswapD(AmoswapD(inst as _)))),
                            _ => None,
                        },
                        0b10 => match (inst >> 12usize) & 0b111 {
                            0b10 => Some(Rv64::Rv64a(Rv64a::LrW(LrW(inst as _)))),
                            0b11 => Some(Rv64::Rv64a(Rv64a::LrD(LrD(inst as _)))),
                            _ => None,
                        },
                        0b11 => match (inst >> 12usize) & 0b111 {
                            0b10 => Some(Rv64::Rv64a(Rv64a::ScW(ScW(inst as _)))),
                            0b11 => Some(Rv64::Rv64a(Rv64a::ScD(ScD(inst as _)))),
                            _ => None,
                        },
                        _ => None,
                    },
                    0b1 => match (inst >> 12usize) & 0b111 {
                        0b10 => Some(Rv64::Rv64a(Rv64a::AmoxorW(AmoxorW(inst as _)))),
                        0b11 => Some(Rv64::Rv64a(Rv64a::AmoxorD(AmoxorD(inst as _)))),
                        _ => None,
                    },
                    0b10 => match (inst >> 12usize) & 0b111 {
                        0b10 => Some(Rv64::Rv64a(Rv64a::AmoorW(AmoorW(inst as _)))),
                        0b11 => Some(Rv64::Rv64a(Rv64a::AmoorD(AmoorD(inst as _)))),
                        _ => None,
                    },
                    0b11 => match (inst >> 12usize) & 0b111 {
                        0b10 => Some(Rv64::Rv64a(Rv64a::AmoandW(AmoandW(inst as _)))),
                        0b11 => Some(Rv64::Rv64a(Rv64a::AmoandD(AmoandD(inst as _)))),
                        _ => None,
                    },
                    0b100 => match (inst >> 12usize) & 0b111 {
                        0b10 => Some(Rv64::Rv64a(Rv64a::AmominW(AmominW(inst as _)))),
                        0b11 => Some(Rv64::Rv64a(Rv64a::AmominD(AmominD(inst as _)))),
                        _ => None,
                    },
                    0b101 => match (inst >> 12usize) & 0b111 {
                        0b10 => Some(Rv64::Rv64a(Rv64a::AmomaxW(AmomaxW(inst as _)))),
                        0b11 => Some(Rv64::Rv64a(Rv64a::AmomaxD(AmomaxD(inst as _)))),
                        _ => None,
                    },
                    0b110 => match (inst >> 12usize) & 0b111 {
                        0b10 => Some(Rv64::Rv64a(Rv64a::AmominuW(AmominuW(inst as _)))),
                        0b11 => Some(Rv64::Rv64a(Rv64a::AmominuD(AmominuD(inst as _)))),
                        _ => None,
                    },
                    0b111 => match (inst >> 12usize) & 0b111 {
                        0b10 => Some(Rv64::Rv64a(Rv64a::AmomaxuW(AmomaxuW(inst as _)))),
                        0b11 => Some(Rv64::Rv64a(Rv64a::AmomaxuD(AmomaxuD(inst as _)))),
                        _ => None,
                    },
                    _ => None,
                },
                0b1100 => match (inst >> 12usize) & 0b111 {
                    0b0 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv64::Rv64i(Rv64i::Add(Add(inst as _)))),
                        0b00001 => Some(Rv64::Rv64m(Rv64m::Mul(Mul(inst as _)))),
                        0b100000 => Some(Rv64::Rv64i(Rv64i::Sub(Sub(inst as _)))),
                        _ => None,
                    },
                    0b1 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv64::Rv64i(Rv64i::Sll(Sll(inst as _)))),
                        0b00001 => Some(Rv64::Rv64m(Rv64m::Mulh(Mulh(inst as _)))),
                        _ => None,
                    },
                    0b10 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv64::Rv64i(Rv64i::Slt(Slt(inst as _)))),
                        0b00001 => Some(Rv64::Rv64m(Rv64m::Mulhsu(Mulhsu(inst as _)))),
                        _ => None,
                    },
                    0b11 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv64::Rv64i(Rv64i::Sltu(Sltu(inst as _)))),
                        0b00001 => Some(Rv64::Rv64m(Rv64m::Mulhu(Mulhu(inst as _)))),
                        _ => None,
                    },
                    0b100 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv64::Rv64i(Rv64i::Xor(Xor(inst as _)))),
                        0b00001 => Some(Rv64::Rv64m(Rv64m::Div(Div(inst as _)))),
                        _ => None,
                    },
                    0b101 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv64::Rv64i(Rv64i::Srl(Srl(inst as _)))),
                        0b00001 => Some(Rv64::Rv64m(Rv64m::Divu(Divu(inst as _)))),
                        0b100000 => Some(Rv64::Rv64i(Rv64i::Sra(Sra(inst as _)))),
                        _ => None,
                    },
                    0b110 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv64::Rv64i(Rv64i::Or(Or(inst as _)))),
                        0b00001 => Some(Rv64::Rv64m(Rv64m::Rem(Rem(inst as _)))),
                        _ => None,
                    },
                    0b111 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv64::Rv64i(Rv64i::And(And(inst as _)))),
                        0b00001 => Some(Rv64::Rv64m(Rv64m::Remu(Remu(inst as _)))),
                        _ => None,
                    },
                    _ => None,
                },
                0b1101 => Some(Rv64::Rv64i(Rv64i::Lui(Lui(inst as _)))),
                0b1110 => match (inst >> 12usize) & 0b111 {
                    0b0 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv64::Rv64i(Rv64i::Addw(Addw(inst as _)))),
                        0b00001 => Some(Rv64::Rv64m(Rv64m::Mulw(Mulw(inst as _)))),
                        0b100000 => Some(Rv64::Rv64i(Rv64i::Subw(Subw(inst as _)))),
                        _ => None,
                    },
                    0b1 => Some(Rv64::Rv64i(Rv64i::Sllw(Sllw(inst as _)))),
                    0b100 => Some(Rv64::Rv64m(Rv64m::Divw(Divw(inst as _)))),
                    0b101 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => Some(Rv64::Rv64i(Rv64i::Srlw(Srlw(inst as _)))),
                        0b00001 => Some(Rv64::Rv64m(Rv64m::Divuw(Divuw(inst as _)))),
                        0b100000 => Some(Rv64::Rv64i(Rv64i::Sraw(Sraw(inst as _)))),
                        _ => None,
                    },
                    0b110 => Some(Rv64::Rv64m(Rv64m::Remw(Remw(inst as _)))),
                    0b111 => Some(Rv64::Rv64m(Rv64m::Remuw(Remuw(inst as _)))),
                    _ => None,
                },
                0b10000 => match (inst >> 25usize) & 0b11 {
                    0b0 => Some(Rv64::Rv64f(Rv64f::FmaddS(FmaddS(inst as _)))),
                    0b1 => Some(Rv64::Rv64d(Rv64d::FmaddD(FmaddD(inst as _)))),
                    0b11 => Some(Rv64::Rv64q(Rv64q::FmaddQ(FmaddQ(inst as _)))),
                    _ => None,
                },
                0b10001 => match (inst >> 25usize) & 0b11 {
                    0b0 => Some(Rv64::Rv64f(Rv64f::FmsubS(FmsubS(inst as _)))),
                    0b1 => Some(Rv64::Rv64d(Rv64d::FmsubD(FmsubD(inst as _)))),
                    0b11 => Some(Rv64::Rv64q(Rv64q::FmsubQ(FmsubQ(inst as _)))),
                    _ => None,
                },
                0b10010 => match (inst >> 25usize) & 0b11 {
                    0b0 => Some(Rv64::Rv64f(Rv64f::FnmsubS(FnmsubS(inst as _)))),
                    0b1 => Some(Rv64::Rv64d(Rv64d::FnmsubD(FnmsubD(inst as _)))),
                    0b11 => Some(Rv64::Rv64q(Rv64q::FnmsubQ(FnmsubQ(inst as _)))),
                    _ => None,
                },
                0b10011 => match (inst >> 25usize) & 0b11 {
                    0b0 => Some(Rv64::Rv64f(Rv64f::FnmaddS(FnmaddS(inst as _)))),
                    0b1 => Some(Rv64::Rv64d(Rv64d::FnmaddD(FnmaddD(inst as _)))),
                    0b11 => Some(Rv64::Rv64q(Rv64q::FnmaddQ(FnmaddQ(inst as _)))),
                    _ => None,
                },
                0b10100 => match (inst >> 27usize) & 0b11111 {
                    0b000 => match (inst >> 25usize) & 0b11 {
                        0b0 => Some(Rv64::Rv64f(Rv64f::FaddS(FaddS(inst as _)))),
                        0b1 => Some(Rv64::Rv64d(Rv64d::FaddD(FaddD(inst as _)))),
                        0b11 => Some(Rv64::Rv64q(Rv64q::FaddQ(FaddQ(inst as _)))),
                        _ => None,
                    },
                    0b001 => match (inst >> 25usize) & 0b11 {
                        0b0 => Some(Rv64::Rv64f(Rv64f::FsubS(FsubS(inst as _)))),
                        0b1 => Some(Rv64::Rv64d(Rv64d::FsubD(FsubD(inst as _)))),
                        0b11 => Some(Rv64::Rv64q(Rv64q::FsubQ(FsubQ(inst as _)))),
                        _ => None,
                    },
                    0b010 => match (inst >> 25usize) & 0b11 {
                        0b0 => Some(Rv64::Rv64f(Rv64f::FmulS(FmulS(inst as _)))),
                        0b1 => Some(Rv64::Rv64d(Rv64d::FmulD(FmulD(inst as _)))),
                        0b11 => Some(Rv64::Rv64q(Rv64q::FmulQ(FmulQ(inst as _)))),
                        _ => None,
                    },
                    0b011 => match (inst >> 25usize) & 0b11 {
                        0b0 => Some(Rv64::Rv64f(Rv64f::FdivS(FdivS(inst as _)))),
                        0b1 => Some(Rv64::Rv64d(Rv64d::FdivD(FdivD(inst as _)))),
                        0b11 => Some(Rv64::Rv64q(Rv64q::FdivQ(FdivQ(inst as _)))),
                        _ => None,
                    },
                    0b100 => match (inst >> 25usize) & 0b11 {
                        0b0 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv64::Rv64f(Rv64f::FsgnjS(FsgnjS(inst as _)))),
                            0b1 => Some(Rv64::Rv64f(Rv64f::FsgnjnS(FsgnjnS(inst as _)))),
                            0b10 => Some(Rv64::Rv64f(Rv64f::FsgnjxS(FsgnjxS(inst as _)))),
                            _ => None,
                        },
                        0b1 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv64::Rv64d(Rv64d::FsgnjD(FsgnjD(inst as _)))),
                            0b1 => Some(Rv64::Rv64d(Rv64d::FsgnjnD(FsgnjnD(inst as _)))),
                            0b10 => Some(Rv64::Rv64d(Rv64d::FsgnjxD(FsgnjxD(inst as _)))),
                            _ => None,
                        },
                        0b11 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv64::Rv64q(Rv64q::FsgnjQ(FsgnjQ(inst as _)))),
                            0b1 => Some(Rv64::Rv64q(Rv64q::FsgnjnQ(FsgnjnQ(inst as _)))),
                            0b10 => Some(Rv64::Rv64q(Rv64q::FsgnjxQ(FsgnjxQ(inst as _)))),
                            _ => None,
                        },
                        _ => None,
                    },
                    0b101 => match (inst >> 25usize) & 0b11 {
                        0b0 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv64::Rv64f(Rv64f::FminS(FminS(inst as _)))),
                            0b1 => Some(Rv64::Rv64f(Rv64f::FmaxS(FmaxS(inst as _)))),
                            _ => None,
                        },
                        0b1 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv64::Rv64d(Rv64d::FminD(FminD(inst as _)))),
                            0b1 => Some(Rv64::Rv64d(Rv64d::FmaxD(FmaxD(inst as _)))),
                            _ => None,
                        },
                        0b11 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv64::Rv64q(Rv64q::FminQ(FminQ(inst as _)))),
                            0b1 => Some(Rv64::Rv64q(Rv64q::FmaxQ(FmaxQ(inst as _)))),
                            _ => None,
                        },
                        _ => None,
                    },
                    0b1000 => match (inst >> 25usize) & 0b11 {
                        0b0 => match (inst >> 20usize) & 0b11111 {
                            0b001 => Some(Rv64::Rv64d(Rv64d::FcvtSD(FcvtSD(inst as _)))),
                            0b011 => Some(Rv64::Rv64q(Rv64q::FcvtSQ(FcvtSQ(inst as _)))),
                            _ => None,
                        },
                        0b1 => match (inst >> 20usize) & 0b11111 {
                            0b000 => Some(Rv64::Rv64d(Rv64d::FcvtDS(FcvtDS(inst as _)))),
                            0b011 => Some(Rv64::Rv64q(Rv64q::FcvtDQ(FcvtDQ(inst as _)))),
                            _ => None,
                        },
                        0b11 => match (inst >> 20usize) & 0b11111 {
                            0b000 => Some(Rv64::Rv64q(Rv64q::FcvtQS(FcvtQS(inst as _)))),
                            0b001 => Some(Rv64::Rv64q(Rv64q::FcvtQD(FcvtQD(inst as _)))),
                            _ => None,
                        },
                        _ => None,
                    },
                    0b1011 => match (inst >> 25usize) & 0b11 {
                        0b0 => Some(Rv64::Rv64f(Rv64f::FsqrtS(FsqrtS(inst as _)))),
                        0b1 => Some(Rv64::Rv64d(Rv64d::FsqrtD(FsqrtD(inst as _)))),
                        0b11 => Some(Rv64::Rv64q(Rv64q::FsqrtQ(FsqrtQ(inst as _)))),
                        _ => None,
                    },
                    0b10100 => match (inst >> 25usize) & 0b11 {
                        0b0 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv64::Rv64f(Rv64f::FleS(FleS(inst as _)))),
                            0b1 => Some(Rv64::Rv64f(Rv64f::FltS(FltS(inst as _)))),
                            0b10 => Some(Rv64::Rv64f(Rv64f::FeqS(FeqS(inst as _)))),
                            _ => None,
                        },
                        0b1 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv64::Rv64d(Rv64d::FleD(FleD(inst as _)))),
                            0b1 => Some(Rv64::Rv64d(Rv64d::FltD(FltD(inst as _)))),
                            0b10 => Some(Rv64::Rv64d(Rv64d::FeqD(FeqD(inst as _)))),
                            _ => None,
                        },
                        0b11 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv64::Rv64q(Rv64q::FleQ(FleQ(inst as _)))),
                            0b1 => Some(Rv64::Rv64q(Rv64q::FltQ(FltQ(inst as _)))),
                            0b10 => Some(Rv64::Rv64q(Rv64q::FeqQ(FeqQ(inst as _)))),
                            _ => None,
                        },
                        _ => None,
                    },
                    0b11000 => match (inst >> 20usize) & 0b11111 {
                        0b000 => match (inst >> 25usize) & 0b11 {
                            0b0 => Some(Rv64::Rv64f(Rv64f::FcvtWS(FcvtWS(inst as _)))),
                            0b1 => Some(Rv64::Rv64d(Rv64d::FcvtWD(FcvtWD(inst as _)))),
                            0b11 => Some(Rv64::Rv64q(Rv64q::FcvtWQ(FcvtWQ(inst as _)))),
                            _ => None,
                        },
                        0b001 => match (inst >> 25usize) & 0b11 {
                            0b0 => Some(Rv64::Rv64f(Rv64f::FcvtWuS(FcvtWuS(inst as _)))),
                            0b1 => Some(Rv64::Rv64d(Rv64d::FcvtWuD(FcvtWuD(inst as _)))),
                            0b11 => Some(Rv64::Rv64q(Rv64q::FcvtWuQ(FcvtWuQ(inst as _)))),
                            _ => None,
                        },
                        0b010 => match (inst >> 25usize) & 0b11 {
                            0b0 => Some(Rv64::Rv64f(Rv64f::FcvtLS(FcvtLS(inst as _)))),
                            0b1 => Some(Rv64::Rv64d(Rv64d::FcvtLD(FcvtLD(inst as _)))),
                            0b11 => Some(Rv64::Rv64q(Rv64q::FcvtLQ(FcvtLQ(inst as _)))),
                            _ => None,
                        },
                        0b011 => match (inst >> 25usize) & 0b11 {
                            0b0 => Some(Rv64::Rv64f(Rv64f::FcvtLuS(FcvtLuS(inst as _)))),
                            0b1 => Some(Rv64::Rv64d(Rv64d::FcvtLuD(FcvtLuD(inst as _)))),
                            0b11 => Some(Rv64::Rv64q(Rv64q::FcvtLuQ(FcvtLuQ(inst as _)))),
                            _ => None,
                        },
                        _ => None,
                    },
                    0b11010 => match (inst >> 20usize) & 0b11111 {
                        0b000 => match (inst >> 25usize) & 0b11 {
                            0b0 => Some(Rv64::Rv64f(Rv64f::FcvtSW(FcvtSW(inst as _)))),
                            0b1 => Some(Rv64::Rv64d(Rv64d::FcvtDW(FcvtDW(inst as _)))),
                            0b11 => Some(Rv64::Rv64q(Rv64q::FcvtQW(FcvtQW(inst as _)))),
                            _ => None,
                        },
                        0b001 => match (inst >> 25usize) & 0b11 {
                            0b0 => Some(Rv64::Rv64f(Rv64f::FcvtSWu(FcvtSWu(inst as _)))),
                            0b1 => Some(Rv64::Rv64d(Rv64d::FcvtDWu(FcvtDWu(inst as _)))),
                            0b11 => Some(Rv64::Rv64q(Rv64q::FcvtQWu(FcvtQWu(inst as _)))),
                            _ => None,
                        },
                        0b010 => match (inst >> 25usize) & 0b11 {
                            0b0 => Some(Rv64::Rv64f(Rv64f::FcvtSL(FcvtSL(inst as _)))),
                            0b1 => Some(Rv64::Rv64d(Rv64d::FcvtDL(FcvtDL(inst as _)))),
                            0b11 => Some(Rv64::Rv64q(Rv64q::FcvtQL(FcvtQL(inst as _)))),
                            _ => None,
                        },
                        0b011 => match (inst >> 25usize) & 0b11 {
                            0b0 => Some(Rv64::Rv64f(Rv64f::FcvtSLu(FcvtSLu(inst as _)))),
                            0b1 => Some(Rv64::Rv64d(Rv64d::FcvtDLu(FcvtDLu(inst as _)))),
                            0b11 => Some(Rv64::Rv64q(Rv64q::FcvtQLu(FcvtQLu(inst as _)))),
                            _ => None,
                        },
                        _ => None,
                    },
                    0b11100 => match (inst >> 25usize) & 0b11 {
                        0b0 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv64::Rv64f(Rv64f::FmvXS(FmvXS(inst as _)))),
                            0b1 => Some(Rv64::Rv64f(Rv64f::FclassS(FclassS(inst as _)))),
                            _ => None,
                        },
                        0b1 => match (inst >> 12usize) & 0b111 {
                            0b0 => Some(Rv64::Rv64d(Rv64d::FmvXD(FmvXD(inst as _)))),
                            0b1 => Some(Rv64::Rv64d(Rv64d::FclassD(FclassD(inst as _)))),
                            _ => None,
                        },
                        0b11 => Some(Rv64::Rv64q(Rv64q::FclassQ(FclassQ(inst as _)))),
                        _ => None,
                    },
                    0b11110 => match (inst >> 25usize) & 0b11 {
                        0b0 => Some(Rv64::Rv64f(Rv64f::FmvSX(FmvSX(inst as _)))),
                        0b1 => Some(Rv64::Rv64d(Rv64d::FmvDX(FmvDX(inst as _)))),
                        _ => None,
                    },
                    _ => None,
                },
                0b11000 => match (inst >> 12usize) & 0b111 {
                    0b0 => Some(Rv64::Rv64i(Rv64i::Beq(Beq(inst as _)))),
                    0b1 => Some(Rv64::Rv64i(Rv64i::Bne(Bne(inst as _)))),
                    0b100 => Some(Rv64::Rv64i(Rv64i::Blt(Blt(inst as _)))),
                    0b101 => Some(Rv64::Rv64i(Rv64i::Bge(Bge(inst as _)))),
                    0b110 => Some(Rv64::Rv64i(Rv64i::Bltu(Bltu(inst as _)))),
                    0b111 => Some(Rv64::Rv64i(Rv64i::Bgeu(Bgeu(inst as _)))),
                    _ => None,
                },
                0b11001 => Some(Rv64::Rv64i(Rv64i::Jalr(Jalr(inst as _)))),
                0b11011 => Some(Rv64::Rv64i(Rv64i::Jal(Jal(inst as _)))),
                0b11100 => match (inst >> 12usize) & 0b111 {
                    0b0 => match (inst >> 25usize) & 0b1111111 {
                        0b00000 => match (inst >> 20usize) & 0b11111 {
                            0b000 => Some(Rv64::Rv64s(Rv64s::Ecall(Ecall(inst as _)))),
                            0b001 => Some(Rv64::Rv64s(Rv64s::Ebreak(Ebreak(inst as _)))),
                            0b010 => Some(Rv64::Rv64s(Rv64s::Uret(Uret(inst as _)))),
                            _ => None,
                        },
                        0b01000 => match (inst >> 20usize) & 0b11111 {
                            0b010 => Some(Rv64::Rv64s(Rv64s::Sret(Sret(inst as _)))),
                            0b100 => Some(Rv64::Rv64s(Rv64s::SfenceVm(SfenceVm(inst as _)))),
                            0b101 => Some(Rv64::Rv64s(Rv64s::Wfi(Wfi(inst as _)))),
                            _ => None,
                        },
                        0b01001 => Some(Rv64::Rv64s(Rv64s::SfenceVma(SfenceVma(inst as _)))),
                        0b10000 => Some(Rv64::Rv64s(Rv64s::Hret(Hret(inst as _)))),
                        0b11000 => Some(Rv64::Rv64s(Rv64s::Mret(Mret(inst as _)))),
                        0b111101 => Some(Rv64::Rv64s(Rv64s::Dret(Dret(inst as _)))),
                        _ => None,
                    },
                    0b1 => Some(Rv64::Rv64s(Rv64s::Csrrw(Csrrw(inst as _)))),
                    0b10 => Some(Rv64::Rv64s(Rv64s::Csrrs(Csrrs(inst as _)))),
                    0b11 => Some(Rv64::Rv64s(Rv64s::Csrrc(Csrrc(inst as _)))),
                    0b101 => Some(Rv64::Rv64s(Rv64s::Csrrwi(Csrrwi(inst as _)))),
                    0b110 => Some(Rv64::Rv64s(Rv64s::Csrrsi(Csrrsi(inst as _)))),
                    0b111 => Some(Rv64::Rv64s(Rv64s::Csrrci(Csrrci(inst as _)))),
                    _ => None,
                },
                _ => None,
            },
            _ => None,
        }
    }
}
