[package]
name = "riscv-inst"
version = "0.1.0"
edition = "2021"

[features]
default = ["m", "c"]
m = []
c = []

[dependencies]
riscv-inst-macros.workspace = true

[build-dependencies]
riscv-c-tables.workspace = true
