[package]
name = "riscv-inst"
version = "0.1.0"
edition = "2021"

[features]
default = ["m", "c"]
m = []
c = []

[dependencies]
num = "0.4.3"

[build-dependencies]
riscv-c-tables = { path = "../riscv-c-tables" }
